### ISSUE TITLE
Ajouter une licence

### ISSUE THREAD

**Issue by nicolas-bonnel** [mdiplo/Medias_francais#1]
Bonjour et merci pour cette initiative.

Ai-je le droit de republier ces données ? Comment puis-je les utiliser pour faire une application ou visualisation ?

Une licence encadrant tout ça permettrait d'y voir plus clair.

**Comment by thibnton** [comment]
Voilà, on a opté pour CC-BY-SA-4.0. 
Ca vous va ?

**Comment by maxlath** [comment]
Bonjour,

une [licence CC0](https://wiki.creativecommons.org/wiki/CC0_use_for_data#Wikidata) serait idéal il me semble : cela permettrait à n'importe qui de réutiliser celles-ci librement, et notamment de les importer dans [Wikidata](https://wikidata.org), ce qui faciliterait leur usage dans Wikipedia [et ailleurs](http://lab.cccb.org/en/wikidata-the-new-rosetta-stone/). L'import pourrait néanmoins toujours créditer le monde diplomatique en [référence](https://www.wikidata.org/wiki/Wikidata:Glossary#Reference)

[Exemple de requête qui pourrait grandement bénéficier de cet import](https://query.wikidata.org/embed.html#SELECT%20%3Fnewspaper%20%3FnewspaperLabel%20%3Fowner%20%3FownerLabel%20%3Fproportion%20%3FproportionLabel%0AWHERE%20{%20%0A%20%20%3Fnewspaper%20wdt%3AP31%2Fwdt%3AP279*%20wd%3AQ11032%20.%0A%20%20%23%20%3Fnewspaper%20wdt%3AP159%2Fwdt%3AP131*%20wd%3AQ142%20.%0A%20%20%3Fnewspaper%20wdt%3AP17%20wd%3AQ142%20.%0A%20%20%3Fnewspaper%20wdt%3AP127%20%3Fowner%20.%0A%20%20OPTIONAL%20{%0A%20%20%20%20%3Fnewspaper%20p%3AP127%20[%20pq%3AP1107%20%3Fproportion%3B%20]%0A%20%20}%0A%20%20SERVICE%20wikibase%3Alabel%20{%20bd%3AserviceParam%20wikibase%3Alanguage%20%22fr%22%20}%0A%20%20FILTER%20NOT%20EXISTS{%20%3Fnewspaper%20wdt%3AP576%20%3Fdate%20}%20%23%20filter-out%20closed%20newspapers%0A}) (basé sur une requête de @jum-s)

cc @wetneb : un import avec [OpenRefine](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine) semblerait adapté, non ?

**Comment by wetneb** [comment]
carrément, les données s'y prêtent très bien!

**Comment by thibnton** [comment]
L'avantage de la CC0 par rapport à la CC-BY ? On avait le souci de renvoyer à la source Diplo dans tous les cas de réutilisation, mais il semble que la CC0 "n'oblige" pas à ceci, ce qui n'est pas forcément un problème, mais il faudrait en discuter.

**Comment by johanfleury** [comment]
@maxlath :
> notamment de les importer dans Wikidata, ce qui faciliterait leur usage dans Wikipedia et ailleurs. 
>

Je ne suis pas un spécialiste, mais la Creative Commons BY-SA est compatible avec les licences de Wikidata et de Wikipedia.

Si je ne me trompe pas, c’est même cette licence qui est utilisée par ces projets.

@nicolas-bonnel :
> si je fais une visualisation de ces données, je dois repartager le code avec la même licence.
>

C’est ce qu'on appelle une licence copyleft, le travail dérivé devra être sous une licence CC BY-SA ou équivalente.

**Comment by wetneb** [comment]
@johanfleury @thibnton justement, Wikidata est sous CC-0, qui n'est pas compatible avec CC BY-SA (justement parce qu'on peut pas satisfaire le Share Alike). Donc si on importe ce dataset on se fait taper sur les doigts.

Je considère personnellement qu'on peut importer du CC-BY dans Wikidata mais beaucoup de gens vous affirmeront le contraire - donc c'est clairement idéal pour nous si vous pouvez le mettre en CC-0. La source sera renseignée au moyen des "références" ajoutées sur chaque claim ajouté à partir du dataset.

Salutations d'un nouvel abonné heureux comme tout o/

**Comment by thibnton** [comment]
Merci pour ces précisions. On a donc modifié en ODC-By pour l'heure, politique des petits pas oblige, qui nous semble la plus adaptée, rapport à notre souci de mention de la source et des usages dérivés : https://opendatacommons.org/licenses/by/1.0/ 

> ODC-BY basically requires that the contributors to the original database be listed.

En effet, on aimerait bien pouvoir garder une trace de tout ce qui pourrait être fait à partir de cette base. Cette license est-elle compatible compatible avec Wikidata ? 

Je laisse l'issue ouverte pour l'heure, je vais continuer à en discuter en interne, notamment avec @BoOz.

**Comment by wetneb** [comment]
> 4.4 Licensing of others. You may not sublicense the Database. Each time
> You communicate the Database, the whole or Substantial part of the
> Contents, or any Derivative Database to anyone else in any way, the
> Licensor offers to the recipient a license to the Database on the same
> terms and conditions as this License. You are not responsible for
> enforcing compliance by third parties with this License, but You may
> enforce any rights that You have over a Derivative Database. You are
> solely responsible for any modifications of a Derivative Database made
> by You or another Person at Your direction. You may not impose any
> further restrictions on the exercise of the rights granted or affirmed
> under this License.

À mon avis ce paragraphe rend l'import en CC-0 difficile - j'imagine que ça correspond à ce cas de "sublicence".
