### ISSUE TITLE
Usage du format tsv

### ISSUE THREAD

**Issue by fzenoni** [mdiplo/Medias_francais#10]
Pourquoi ne pas utiliser un format texte plus lisible, tel que csv?
La définition des cases n'étant pas actuellement rigoureuse, GitHub n'est pas capable de visualiser correctement les données (https://help.github.com/articles/rendering-csv-and-tsv-data/). En particulier, beaucoup de lignes n'ont pas le nombre correct de colonnes, mais vu l'usage du tab au lieu de la virgule, ceci reste difficile à détecter.
On est donc forcé d'ajouter des options supplémentaires lorsque l'on importe les tables dans un langage de programmation. Ceci pourrait-être évité si les fichiers étaient bien structurés.

**Comment by BoOz** [comment]
Bonjour,

Il y avait une erreur de colonage au moment ou vous avez regardé le fichier. C'est désormais réparé. Le format tsv est aussi lisible que le csv quand il n'y a pas d'erreur. Voici comment l'affiche Github : https://github.com/mdiplo/Medias_francais/blob/master/medias_francais.tsv

<img width="975" alt="capture d ecran 2018-08-29 17 54 17" src="https://user-images.githubusercontent.com/356122/44799586-978f1600-abb4-11e8-8280-52bae988f6f7.png">

L'avantage de ce format c'est qu'on peut le copier coller directement dans un tableur (Excel, Google Sheet etc), ou bien le lire avec un langage de programmation (SPIP par exemple avec la [boucle DATA](https://www.spip.net/fr_article6434.html)).

**Comment by fzenoni** [comment]
Il y a 19 colonnes vides, que vous auriez pu plus facilement détecter dans la source avec l'usage du .csv, grâce à la présence de virgules dans la première ligne. J'ai corrigé ce problème dans un Pull Request (https://github.com/mdiplo/Medias_francais/pull/11) tout en conservant le format .tsv.
![empty_columns](https://user-images.githubusercontent.com/6040873/44837485-0e222700-ac3a-11e8-8883-d3fc6319e402.png)

Pour information, le format csv est tout aussi bien supporté par les tableurs et les langages de programmation.
