### ISSUE TITLE
Comment contribuer ?

### ISSUE THREAD

**Issue by Asenar** [mdiplo/Medias_francais#15]
Bonjour,

comment procéder pour contribuer à la liste ? Une procédure à suivre serait la bienvenue dans le README :)

Là je tombe sur un potentiel oubli (en comparant avec une ancienne version refaite à la main dans un googlesheet qui date de l'année dernière). il y avait Alain Weil parmi les propriétaires de BFMTV (via Nextregie, ou NextRadioTV, mais ça a peut être encore changé de nom peut être en Altice-SFR, j'ai pas creusé)

**Comment by thibnton** [comment]
Il a quitté la base, tout appartient désormais à Altice France (ex- SFR Groupe). 
Cf. https://github.com/mdiplo/Medias_francais/commit/b4490eeed1aaa98c14ca479acdbae4cb6624fadf

**Comment by Asenar** [comment]
Selon la Wikipedia, le PDF d'[Altice France est Alain Weill](https://fr.wikipedia.org/wiki/Altice_France).

Et je n'ai pas trouvé d'info plus récente…

EDIT: si le site officiel d'Altice est à jour, il est [CEO d'Altice France](http://altice.net/board-directors)
