### ISSUE TITLE
Référencement sur data.gouv.fr

### ISSUE THREAD

**Issue by taniki** [mdiplo/Medias_francais#16]
Bonjour,

je suis actuellement développeur sur la plateforme data.gouv.fr et j'étais entrain de faire pivoter les données titres <-> éditeurs <-> subventions fournis par le ministère de la culture avec les données de la base SIRENE (entreprises) fournie par l'INSEE. J'ai plutôt de bons résultats mais il me manquait des données sur les regroupements. Votre jeu de données est très précieux dans ce sens et il me semble que ça serait une bonne chose que vous le référenciez sur la plateforme afin que les différentes personnes ayant usage puisse facilement le trouver.

**Comment by Asenar** [comment]
Bonjour,

je t'invite à venir faire un tour sur le salon de discussion mentionné sur [ce dépôt](https://github.com/Vict0rSch/metada), on réfléchit justement à une manière de mettre en commun nos ressources en partant de ces données :)

**Comment by BoOz** [comment]
Hello,

Ca serait bien de prévoir un flux de retour, pour quo'n puisse récupérer ici certaines infos issues de data.gouv.fr ou bien metalab.

@taniki tu es allé au bout de ta démarche ?

**Comment by taniki** [comment]
Pas complètement au bout mais il ne me reste pas grand chose. Je pense pouvoir m'y remettre dans le courant du mois de décembre.

J'ai commencé à mettre mes expérimentations ici : https://github.com/taniki/notebooks/tree/master/data.gouv.fr/presse.

J'ai aussi commencé à regarder pour faire des croisements avec wikipedia/wikidata.

La prochaine étape avant d'avoir un truc robuste, c'est plutôt de faire des tables de pivot/jointure plutôt que de se baser sur la simple identité de chaines de caractères. Ça ne sera pas très complexe (:

**Comment by BoOz** [comment]
> subventions fournis par le ministère de la culture

Le fichier est là, il y a à la fois les subventions et la diffusion.
https://www.data.gouv.fr/fr/datasets/aides-a-la-presse-classement-des-titres-de-presse-aides-1/

**Comment by johanricher** [comment]
J'envisage de faire une PR pour ajouter une colonne "wikidata_id" contenant tous les identifiants Wikidata pour tous les médias référencés dans `medias_francais.tsv`. Who's in ?
