### ISSUE TITLE
Vente de 49% des parts de "Le Monde libre" de Mathieu Pigasse à "Daniel Kretinsky"

### ISSUE THREAD

**Issue by julienfastre** [mdiplo/Medias_francais#17]
Bonjour,

J'imagine que ceci a été noté: 

https://www.lemonde.fr/actualite-medias/article/2018/10/25/le-monde-le-pole-d-independance-du-journal-obtient-un-droit-de-veto-en-cas-de-changement-de-controle_5374512_3236.html

**Comment by thibnton** [comment]
En effet, mais merci quand même.

**Comment by thibnton** [comment]
Je récapitule en vue d'une nouvelle mise à jour : 
-  Rajouter i24News au groupe Altice
- Lagardère a vendu Elle, Version Femina, Art & Décoration, Télé 7 Jours, France Dimanche, Ici Paris et Public à Daniel Kretinsky (Czech Media Invest) https://www.bfmtv.com/economie/lagardere-conclut-la-vente-de-ses-magazines-a-czech-media-invest-1537630.html
- Pigasse a vendu 49 % de sa holding actionnaire du « Monde » à ce même Daniel Kretinsky
