### ISSUE TITLE
Base de données Neo4J

### ISSUE THREAD

**Issue by WittR** [mdiplo/Medias_francais#20]
Bonjour,

J'ai effectué un petit travail sur la base pour m'amuser, j'avoue ne pas avoir vraiment pris compte de ce qui a pu être fait ici, c'est à l'origine un travail perso pour monter en compétences techniques. Donc vous prenez ce qui vous plait ;) 

[Lien vers mon repository](https://github.com/WittR/Medias_francais)

### Pour résumer : 

-  J'ai créé une base une base Neo4J
- J'ai re-exporté les données issues de la base en modifiant un peu la forme

### Les choses que j'ai vues et qui posent question : 

- Les apostrophes utilisées ne sont pas toujours les mêmes, ce qui pose problème pour identifier les individus (j'ai vu qu'une demande de pull avait été formulée dans ce sens)
- La personne morale "_Les Nouvelles Éditions_" ne semble pas être utilisée (doublon ?)
-  On a deux fois les relations entre _République Française, Renault et le Groupe Perdriel_ 

### J'explique un peu plus ce qui a été fait : 

-  Neo4J est une base de données orientée graphe, on stocke l'information sous forme de nœuds et de relations (ça tombe bien, voir les deux images [ici](https://github.com/WittR/Medias_francais).)

![exemple_zoom_relations](https://user-images.githubusercontent.com/14804697/50093413-dce15d00-0210-11e9-86d9-f50fedce6fa5.png)

-  Neo4J dispose d'une édition communautaire libre et gratuite (c'est celle que j'utilise), elle est limitée mais bien suffisante pour les besoins actuels
- **Il pourrait être possible d'intégrer un graphe comme ceux du navigateur Neo4J à une page HTML ce qui peut intéresser LMD (je ne me suis pas encore penché sur la question)** 

- J'ai créé deux nouveaux fichiers qui rassemblent d'une part les acteurs d'autres part les relations. Concernant les relations, j'utilises désormais les identifiants pour désigner l'origine et la cible. Chaque relation dispose elle-même d'un identifiant. 

![table_relations](https://user-images.githubusercontent.com/14804697/50093506-2b8ef700-0211-11e9-914c-a39997401565.png)

- L'ensemble du travail a été fait en python 3 et en utilisant la bibliothèque neo4J. Le fichier python disponible dans le repository dispose de fonctions qui permettent de créer la base neo4J depuis les fichiers disponibles sur la branche master et de créer les nouveaux fichiers. Pour fonctionner, le programme nécessite _a minima_ d'une base Neo4j qui tourne en local sur votre PC (gratuit, disponible sur le site)

Voilà c'était amusant,
Débizou.

**Comment by thierrymarianne** [comment]
Merci ! Une PR a été ouverte afin de régler le problème des apostrophes : https://github.com/mdiplo/Medias_francais/pull/18

**Comment by ynnk** [comment]
Voici un autre exercice un peu similaire à base de tableau csv et un parser en ligne.
https://github.com/ynnk/Medias_francais
