### ISSUE TITLE
Alain Weill prend 51% de L'Express à titre personnel

### ISSUE THREAD

**Issue by thibnton** [mdiplo/Medias_francais#22]
Le PDG de SFR et fondateur de NextRadioTV va prendre à titre personnel 51 % du capital de l'hebdomadaire, SFR (Altice) restant actionnaire à 49%.

Source : [Le Figaro](http://www.lefigaro.fr/medias/2019/02/12/20004-20190212ARTFIG00117-les-projets-d-alain-weill-pour-l-express.php)

**Comment by tuxayo** [comment]
Il semble que ça a été intégré: https://github.com/mdiplo/Medias_francais/commit/99f8a0a1948d088eb1443fc3e89066dbdfb2ddb5
