### ISSUE TITLE
BeIn Sports

### ISSUE THREAD

**Issue by wpinaud** [mdiplo/Medias_francais#23]
Bonjour,
Il y a t il une raison pourquoi le media BeIN sports n'apparaît pas dans la liste des médias français?
Cordialement

**Comment by thibnton** [comment]
Parce qu'il ne s'agit pas d'un «  média d’information qui “ fait l’opinion”
» ?

> Voir la méthodologie : https://www.monde-diplomatique.fr/cartes/PPA
