### ISSUE TITLE
[suggestion] Lister les subventions également ?

### ISSUE THREAD

**Issue by patheticcockroach** [mdiplo/Medias_francais#3]
Bonjour,

Merci pour ces données intéressantes.
Pour aller plus loin dans le "suivez les liens capitalistiques pour savoir qui commande", ça serait sans doute pertinent d'intégrer, dans de futures versions, les données sur les subventions, si vous les trouvez.

**Comment by BoOz** [comment]
Bonjour, cela serait intéressant en effet. Mais détailler les subventions est un exercice fastidieux tant elles recouvrent des natures diverses (aides directes, aides indirectes, TVA réduite, etc...).

Les données ne sont pas toutes immédiatement disponibles, et n'en mettre qu'une partie peut-être trompeur.
