### ISSUE TITLE
Entité incorrecte ? « Länder de République fédérale d’Allemagne »

### ISSUE THREAD

**Issue by racine-p-a** [mdiplo/Medias_francais#30]
Le terme : ___Länder de République fédérale d’Allemagne___ est-il correct ?

--> Un land est une région administrative de l'Allemagne.
--> Länder est le pluriel de Land en allemand.
--> Il vaudrait peut-être renommer simplement en *République d'Allemagne*.

**Comment by suzygd** [comment]
Bonjour, l'entité « Länder de République fédérale d'Allemagne » est redevenue « République fédérale d'Allemagne ». La confusion tient au groupement de 9 diffuseurs régionaux (ARD) propriétaire à hauteur de 50% d'Arte Deutschland.
Merci !
