### ISSUE TITLE
[README.md] Carte v.17 Not found

### ISSUE THREAD

**Issue by Kuchengeschmack** [mdiplo/Medias_francais#36]
Bonjour, le lien vers la carte v.17 dans le Readme.md renvoie vers une page blanche "Not found".

Le lien en question : ![Carte v.17](https://www.monde-diplomatique.fr/IMG/png/ppa17.png)

**Comment by taniki** [comment]
#35 devrait corrigé le lien vers le cache de l'image.

La bonne url finale est https://www.monde-diplomatique.fr/IMG/png/poster_medias_francais_8060-v17-4.png par ailleurs.
